In [1]:
import pandas as pd

In [ ]:
df  = pd.read_csv("data/patients.csv")
df.head()

                name  age
0  Richard Rodriguez   24
1     Shannon Walker    6
2       Julia Torres   24
3    Crystal Johnson   32
4        Garrett Lin   25

get cell value using at

In [22]:
df.at[4,'name']
df .at[999,'name']

'Lorraine Turner'

In [37]:
# set the value 
df.at[4,'name'] = 'karthikeyan'
df

,patient_id,name,age,arrival_date,departure_date,service,satisfaction
0,PAT-09484753,Richard Rodriguez,24,2025-03-16,2025-03-22,surgery,61
1,PAT-f0644084,Shannon Walker,6,2025-12-13,2025-12-14,surgery,83
2,PAT-ac6162e4,Julia Torres,24,2025-06-29,2025-07-05,general_medicine,83
3,PAT-3dda2bb5,Crystal Johnson,32,2025-10-12,2025-10-23,emergency,81
4,PAT-08591375,karthikeyan,25,2025-02-18,2025-02-25,ICU,76
...,...,...,...,...,...,...,...
995,PAT-a01bf534,Amber Vang,26,2025-12-02,2025-12-04,emergency,91
996,PAT-87fa07bd,Martha Smith,89,2025-11-18,2025-11-30,emergency,99
997,PAT-8f07e894,Jennifer James,72,2025-12-12,2025-12-21,ICU,69
998,PAT-4ae301e1,Kara Hernandez,47,2025-02-08,2025-02-20,ICU,61
999,PAT-e2ef9c5f,Lorraine Turner,64,2025-05-04,2025-05-08,general_medicine,83

In [24]:
# get value of cell using indexat
df.iat[4,1]

# set the value using index at
df.iat[4,2] = 20

In [29]:
#  get cell value using location
df.loc[4,'name']
df.loc[0]
df.loc[:20 ,'name':'age']
df.loc[20: ,'name':'age']

                 name  age
20   Elizabeth Kelley   34
21      Dustin Jordan   45
22      Mary Marshall   13
23     Daniel Kennedy   73
24    Rebecca Jackson   18
..                ...  ...
995        Amber Vang   26
996      Martha Smith   89
997    Jennifer James   72
998    Kara Hernandez   47
999   Lorraine Turner   64

[980 rows x 2 columns]

In [40]:
# get cell value using index location
df.iloc[:,1:3]

                  name  age
0    Richard Rodriguez   24
1       Shannon Walker    6
2         Julia Torres   24
3      Crystal Johnson   32
4          karthikeyan   25
..                 ...  ...
995         Amber Vang   26
996       Martha Smith   89
997     Jennifer James   72
998     Kara Hernandez   47
999    Lorraine Turner   64

[1000 rows x 2 columns]

In [41]:
# combination of cell handling
df.loc[4].at['name']

'karthikeyan'

2. rows values handling

In [54]:
import pandas as pd
df = pd.read_csv("data/patients.csv")
df.head()

,patient_id,name,age,arrival_date,departure_date,service,satisfaction
0,PAT-09484753,Richard Rodriguez,24,2025-03-16,2025-03-22,surgery,61
1,PAT-f0644084,Shannon Walker,6,2025-12-13,2025-12-14,surgery,83
2,PAT-ac6162e4,Julia Torres,24,2025-06-29,2025-07-05,general_medicine,83
3,PAT-3dda2bb5,Crystal Johnson,32,2025-10-12,2025-10-23,emergency,81
4,PAT-08591375,Garrett Lin,25,2025-02-18,2025-02-25,ICU,76

In [51]:
# get row values
df.loc[4]

patient_id        PAT-08591375
name               Garrett Lin
age                         25
arrival_date        2025-02-18
departure_date      2025-02-25
service                    ICU
satisfaction                76
Name: 4, dtype: object

In [56]:
df.loc[4]= ['PAT-1234','karthikeyan',20,'2006-02-27','2026-08-05','general_medicine',100]

In [57]:
df

,patient_id,name,age,arrival_date,departure_date,service,satisfaction
0,PAT-09484753,Richard Rodriguez,24,2025-03-16,2025-03-22,surgery,61
1,PAT-f0644084,Shannon Walker,6,2025-12-13,2025-12-14,surgery,83
2,PAT-ac6162e4,Julia Torres,24,2025-06-29,2025-07-05,general_medicine,83
3,PAT-3dda2bb5,Crystal Johnson,32,2025-10-12,2025-10-23,emergency,81
4,PAT-1234,karthikeyan,20,2006-02-27,2026-08-05,general_medicine,100
...,...,...,...,...,...,...,...
995,PAT-a01bf534,Amber Vang,26,2025-12-02,2025-12-04,emergency,91
996,PAT-87fa07bd,Martha Smith,89,2025-11-18,2025-11-30,emergency,99
997,PAT-8f07e894,Jennifer James,72,2025-12-12,2025-12-21,ICU,69
998,PAT-4ae301e1,Kara Hernandez,47,2025-02-08,2025-02-20,ICU,61
999,PAT-e2ef9c5f,Lorraine Turner,64,2025-05-04,2025-05-08,general_medicine,83