Dataframe

In [1]:
import pandas as pd

In [4]:
apple =['Apple',60]
banana =['banana',50]
fruits = [apple,banana]
fruits

[['Apple', 60], ['banana', 50]]

In [10]:
df=pd.DataFrame(fruits)
df

        0   1
0   Apple  60
1  banana  50

In [13]:
df.columns = ['fruits','price']
df

   fruits  price
0   Apple     60
1  banana     50

Dataframe using tuple

In [21]:
apple =('Apple',60)
banana =('banana',50)
fruits = (apple,banana)

df = pd.DataFrame(fruits)
df.columns=['Fruits','price']
df

   Fruits  price
0   Apple     60
1  banana     50

Dataframe using dictionary

In [29]:
apple ={'name':'Apple','price':50}
banana ={'name':'banana','price':10}
mango ={'name':'mango','price':150}
fruits = (apple,banana,mango)
df =pd.DataFrame(fruits)
# df.columns =['fruits','price1']
df

     name  price
0   Apple     50
1  banana     10
2   mango    150

In [32]:
fruits ={
    'name':['apple','banana','mango'],
    'price':[50,10,100]
}
fruits

{'name': ['apple', 'banana', 'mango'], 'price': [50, 10, 100]}

In [36]:
df =pd.DataFrame(fruits)
df

     name  price
0   apple     50
1  banana     10
2   mango    100