In [2]:
import pandas as pd
df = pd.read_csv("data/patients.csv")
df.head(10)

,patient_id,name,age,arrival_date,departure_date,service,satisfaction
0,PAT-09484753,Richard Rodriguez,24,2025-03-16,2025-03-22,surgery,61
1,PAT-f0644084,Shannon Walker,6,2025-12-13,2025-12-14,surgery,83
2,PAT-ac6162e4,Julia Torres,24,2025-06-29,2025-07-05,general_medicine,83
3,PAT-3dda2bb5,Crystal Johnson,32,2025-10-12,2025-10-23,emergency,81
4,PAT-08591375,Garrett Lin,25,2025-02-18,2025-02-25,ICU,76
5,PAT-f4b29bae,Diana May,83,2025-06-26,2025-06-30,emergency,81
6,PAT-283cda07,William Herrera,62,2025-12-26,2025-12-27,emergency,66
7,PAT-5b61868c,Ashley Waller,0,2025-05-21,2025-06-04,ICU,82
8,PAT-f9c8afa6,Victor Baker,50,2025-07-30,2025-08-13,general_medicine,91
9,PAT-5290be70,Jeffrey Chandler,29,2025-11-01,2025-11-14,emergency,88

In [3]:
# get continuous range of rows
df.loc[0:6]

,patient_id,name,age,arrival_date,departure_date,service,satisfaction
0,PAT-09484753,Richard Rodriguez,24,2025-03-16,2025-03-22,surgery,61
1,PAT-f0644084,Shannon Walker,6,2025-12-13,2025-12-14,surgery,83
2,PAT-ac6162e4,Julia Torres,24,2025-06-29,2025-07-05,general_medicine,83
3,PAT-3dda2bb5,Crystal Johnson,32,2025-10-12,2025-10-23,emergency,81
4,PAT-08591375,Garrett Lin,25,2025-02-18,2025-02-25,ICU,76
5,PAT-f4b29bae,Diana May,83,2025-06-26,2025-06-30,emergency,81
6,PAT-283cda07,William Herrera,62,2025-12-26,2025-12-27,emergency,66

In [6]:
# get intermediate rows like 1,3,5
df.loc[[1,8,4]]

,patient_id,name,age,arrival_date,departure_date,service,satisfaction
1,dummy,dummy,6,2025-12-13,2025-12-14,surgery,83
8,PAT-f9c8afa6,Victor Baker,50,2025-07-30,2025-08-13,general_medicine,91
4,dummy,dummy,25,2025-02-18,2025-02-25,ICU,76

In [9]:
# get column values
df.loc[:,'name':'service']
df.loc[:,['name','age','service']]

                  name  age           service
0    Richard Rodriguez   24           surgery
1                dummy    6           surgery
2                dummy   24  general_medicine
3                dummy   32         emergency
4                dummy   25               ICU
..                 ...  ...               ...
995         Amber Vang   26         emergency
996       Martha Smith   89         emergency
997     Jennifer James   72               ICU
998     Kara Hernandez   47               ICU
999    Lorraine Turner   64  general_medicine

[1000 rows x 3 columns]