In [29]:
import pandas as pd
df = pd.read_csv('data/patients.csv')

In [30]:
df.head(5)

,patient_id,name,age,arrival_date,departure_date,service,satisfaction
0,PAT-09484753,Richard Rodriguez,24,2025-03-16,2025-03-22,surgery,61
1,PAT-f0644084,Shannon Walker,6,2025-12-13,2025-12-14,surgery,83
2,PAT-ac6162e4,Julia Torres,24,2025-06-29,2025-07-05,general_medicine,83
3,PAT-3dda2bb5,Crystal Johnson,32,2025-10-12,2025-10-23,emergency,81
4,PAT-08591375,Garrett Lin,25,2025-02-18,2025-02-25,ICU,76

In [31]:
df=df.set_index('patient_id')

In [14]:
df

,name,age,arrival_date,departure_date,service,satisfaction
patient_id,,,,,,
PAT-09484753,Richard Rodriguez,24,2025-03-16,2025-03-22,surgery,61
PAT-f0644084,Shannon Walker,6,2025-12-13,2025-12-14,surgery,83
PAT-ac6162e4,Julia Torres,24,2025-06-29,2025-07-05,general_medicine,83
PAT-3dda2bb5,Crystal Johnson,32,2025-10-12,2025-10-23,emergency,81
PAT-08591375,Garrett Lin,25,2025-02-18,2025-02-25,ICU,76
...,...,...,...,...,...,...
PAT-a01bf534,Amber Vang,26,2025-12-02,2025-12-04,emergency,91
PAT-87fa07bd,Martha Smith,89,2025-11-18,2025-11-30,emergency,99
PAT-8f07e894,Jennifer James,72,2025-12-12,2025-12-21,ICU,69
PAT-4ae301e1,Kara Hernandez,47,2025-02-08,2025-02-20,ICU,61
PAT-e2ef9c5f,Lorraine Turner,64,2025-05-04,2025-05-08,general_medicine,83