Arithmetic operation

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame([[10,20,30],
                  [5,25,15],
                  [2,20,10]])
    
df.columns =['A','B','C']
df

    A   B   C
0  10  20  30
1   5  25  15
2   2  20  10

In [6]:
# addition
# df+1
df.add(1)

    A   B   C
0  11  21  31
1   6  26  16
2   3  21  11

In [9]:
#substraction
# df - 1
# df.sub(1)
df.subtract(2)

   A   B   C
0  8  18  28
1  3  23  13
2  0  18   8

In [ ]:
#multiplication
# df * 2
# df.mul(2)
# df.multiply(2)

    A   B   C
0  20  40  60
1  10  50  30
2   4  40  20

In [14]:
# division
# df /2
# df.div(2)
df.divide(2)

     A     B     C
0  5.0  10.0  15.0
1  2.5  12.5   7.5
2  1.0  10.0   5.0

In [16]:
# floor division or intger divison
# df // 2
df.floordiv(2)

   A   B   C
0  5  10  15
1  2  12   7
2  1  10   5

In [18]:
# modulus
# df % 2
df.mod(2)

   A  B  C
0  0  0  0
1  1  1  1
2  0  0  0

In [20]:
# power
# df ** 2
df.pow(2)

     A    B    C
0  100  400  900
1   25  625  225
2    4  400  100

In [22]:
# on series
df['A'] + 2
df['A'].divmod(2)

(0    5
 1    2
 2    1
 Name: A, dtype: int64,
 0    0
 1    1
 2    0
 Name: A, dtype: int64)

In [ ]:
# adding two colunm each other

In [26]:
df['D']=df['A'] .add(df['B'])
df

    A   B   C   D
0  10  20  30  30
1   5  25  15  30
2   2  20  10  22