In [1]:
import pandas as pd

In [2]:
df= pd.DataFrame({'Qty':[10,20,30],
                 'Price':[100,200,300]})
df

   Qty  Price
0   10    100
1   20    200
2   30    300

In [12]:
# df['Total'] = df["Qty"] * df['Price']
df.eval('Total = Qty * Price ')

   Qty  Price  Total
0   10    100   1000
1   20    200   4000
2   30    300   9000