Assign Function - to build transformation piplines

In [1]:
import pandas as pd

In [5]:
df= pd.read_csv("../data/cars.csv")
df.head()

,car name,mpg,cylinders,displacement,horsepower,acceleration,model year,origin
0,chevrolet chevelle malibu,18.0,8,307.0,130,12.0,70,USA
1,buick skylark 320,15.0,8,350.0,165,11.5,70,USA
2,plymouth satellite,18.0,8,318.0,150,11.0,70,USA
3,amc rebel sst,16.0,8,304.0,150,12.0,70,USA
4,ford torino,17.0,8,302.0,140,10.5,70,USA

In [6]:
def convert_kg_to_ton(weight):
    return weight/1000
def convert_hp_to_kw(hp):
    return hp*0.745

In [ ]:
df['horsepower']=pd.to_numeric(df['horsepower'],errors='coerce')

In [41]:
df.assign(horsepower = convert_hp_to_kw(df['horsepower']))

,car name,mpg,cylinders,displacement,horsepower,acceleration,model year,origin,kw
0,chevrolet chevelle malibu,18.0,8,307.0,96.850,12.0,70,USA,96.850
1,buick skylark 320,15.0,8,350.0,122.925,11.5,70,USA,122.925
2,plymouth satellite,18.0,8,318.0,111.750,11.0,70,USA,111.750
3,amc rebel sst,16.0,8,304.0,111.750,12.0,70,USA,111.750
4,ford torino,17.0,8,302.0,104.300,10.5,70,USA,104.300
...,...,...,...,...,...,...,...,...,...
393,ford mustang gl,27.0,4,140.0,64.070,15.6,82,USA,64.070
394,vw pickup,44.0,4,97.0,38.740,24.6,82,IND,38.740
395,dodge rampage,32.0,4,135.0,62.580,11.6,82,USA,62.580
396,ford ranger,28.0,4,120.0,58.855,18.6,82,USA,58.855
397,chevy s-10,31.0,4,119.0,61.090,19.4,82,USA,61.090

In [37]:
df

,car name,mpg,cylinders,displacement,horsepower,acceleration,model year,origin,kw
0,chevrolet chevelle malibu,18.0,8,307.0,130.0,12.0,70,USA,96.850
1,buick skylark 320,15.0,8,350.0,165.0,11.5,70,USA,122.925
2,plymouth satellite,18.0,8,318.0,150.0,11.0,70,USA,111.750
3,amc rebel sst,16.0,8,304.0,150.0,12.0,70,USA,111.750
4,ford torino,17.0,8,302.0,140.0,10.5,70,USA,104.300
...,...,...,...,...,...,...,...,...,...
393,ford mustang gl,27.0,4,140.0,86.0,15.6,82,USA,64.070
394,vw pickup,44.0,4,97.0,52.0,24.6,82,IND,38.740
395,dodge rampage,32.0,4,135.0,84.0,11.6,82,USA,62.580
396,ford ranger,28.0,4,120.0,79.0,18.6,82,USA,58.855
397,chevy s-10,31.0,4,119.0,82.0,19.4,82,USA,61.090

In [36]:
df=df.drop('horespower',axis=1)