drop columns

In [3]:
import pandas as pd
df = pd.read_csv('../data/patients.csv')
df.head()

,patient_id,name,age,arrival_date,departure_date,service,satisfaction
0,PAT-09484753,Richard Rodriguez,24,2025-03-16,2025-03-22,surgery,61
1,PAT-f0644084,Shannon Walker,6,2025-12-13,2025-12-14,surgery,83
2,PAT-ac6162e4,Julia Torres,24,2025-06-29,2025-07-05,general_medicine,83
3,PAT-3dda2bb5,Crystal Johnson,32,2025-10-12,2025-10-23,emergency,81
4,PAT-08591375,Garrett Lin,25,2025-02-18,2025-02-25,ICU,76

In [9]:
df=df.drop(['arrival_date','departure_date'],axis =1)

In [11]:
df

       patient_id               name  age           service  satisfaction
0    PAT-09484753  Richard Rodriguez   24           surgery            61
1    PAT-f0644084     Shannon Walker    6           surgery            83
2    PAT-ac6162e4       Julia Torres   24  general_medicine            83
3    PAT-3dda2bb5    Crystal Johnson   32         emergency            81
4    PAT-08591375        Garrett Lin   25               ICU            76
..            ...                ...  ...               ...           ...
995  PAT-a01bf534         Amber Vang   26         emergency            91
996  PAT-87fa07bd       Martha Smith   89         emergency            99
997  PAT-8f07e894     Jennifer James   72               ICU            69
998  PAT-4ae301e1     Kara Hernandez   47               ICU            61
999  PAT-e2ef9c5f    Lorraine Turner   64  general_medicine            83

[1000 rows x 5 columns]

In [12]:
df.drop(columns =['service','satisfaction'])

       patient_id               name  age
0    PAT-09484753  Richard Rodriguez   24
1    PAT-f0644084     Shannon Walker    6
2    PAT-ac6162e4       Julia Torres   24
3    PAT-3dda2bb5    Crystal Johnson   32
4    PAT-08591375        Garrett Lin   25
..            ...                ...  ...
995  PAT-a01bf534         Amber Vang   26
996  PAT-87fa07bd       Martha Smith   89
997  PAT-8f07e894     Jennifer James   72
998  PAT-4ae301e1     Kara Hernandez   47
999  PAT-e2ef9c5f    Lorraine Turner   64

[1000 rows x 3 columns]