Truncate the rows

In [2]:
import pandas as pd
df = pd.read_csv("../data/patients.csv")
df.head(20)

,patient_id,name,age,arrival_date,departure_date,service,satisfaction
0,PAT-09484753,Richard Rodriguez,24,2025-03-16,2025-03-22,surgery,61
1,PAT-f0644084,Shannon Walker,6,2025-12-13,2025-12-14,surgery,83
2,PAT-ac6162e4,Julia Torres,24,2025-06-29,2025-07-05,general_medicine,83
3,PAT-3dda2bb5,Crystal Johnson,32,2025-10-12,2025-10-23,emergency,81
4,PAT-08591375,Garrett Lin,25,2025-02-18,2025-02-25,ICU,76
5,PAT-f4b29bae,Diana May,83,2025-06-26,2025-06-30,emergency,81
6,PAT-283cda07,William Herrera,62,2025-12-26,2025-12-27,emergency,66
7,PAT-5b61868c,Ashley Waller,0,2025-05-21,2025-06-04,ICU,82
8,PAT-f9c8afa6,Victor Baker,50,2025-07-30,2025-08-13,general_medicine,91
9,PAT-5290be70,Jeffrey Chandler,29,2025-11-01,2025-11-14,emergency,88
10,PAT-003ce690,Larry Dixon,29,2025-01-19,2025-01-21,ICU,60
11,PAT-18f78014,Kenneth Scott,77,2025-06-24,2025-06-26,general_medicine,61
12,PAT-69dc0dc1,April Frost,37,2025-11-15,2025-11-19,general_medicine,60
13,PAT-95afe21e,Michelle Harmon,7,2025-02-24,2025-03-03,emergency,62
14,PAT-cc50ad71,Helen Jones,31,2025-06-11,2025-06-23,surgery,92
15,PAT-0beb4754,Erin Edwards,86,2025-10-15,2025-10-17,general_medicine,66
16,PAT-3223420e,Michelle Evans,7,2025-11-09,2025-11-16,emergency,62
17,PAT-f0682772,Jason Powell,87,2025-09-12,2025-09-25,general_medicine,67
18,PAT-af65396f,Cameron Fisher,53,2025-08-27,2025-09-01,emergency,62
19,PAT-dbbf6d1f,Megan Orr,50,2025-04-02,2025-04-10,emergency,93

In [5]:
df=df.truncate(10,21,axis=0)

In [6]:
df

,patient_id,name,age,arrival_date,departure_date,service,satisfaction
10,PAT-003ce690,Larry Dixon,29,2025-01-19,2025-01-21,ICU,60
11,PAT-18f78014,Kenneth Scott,77,2025-06-24,2025-06-26,general_medicine,61
12,PAT-69dc0dc1,April Frost,37,2025-11-15,2025-11-19,general_medicine,60
13,PAT-95afe21e,Michelle Harmon,7,2025-02-24,2025-03-03,emergency,62
14,PAT-cc50ad71,Helen Jones,31,2025-06-11,2025-06-23,surgery,92
15,PAT-0beb4754,Erin Edwards,86,2025-10-15,2025-10-17,general_medicine,66
16,PAT-3223420e,Michelle Evans,7,2025-11-09,2025-11-16,emergency,62
17,PAT-f0682772,Jason Powell,87,2025-09-12,2025-09-25,general_medicine,67
18,PAT-af65396f,Cameron Fisher,53,2025-08-27,2025-09-01,emergency,62
19,PAT-dbbf6d1f,Megan Orr,50,2025-04-02,2025-04-10,emergency,93
20,PAT-5e3f8747,Elizabeth Kelley,34,2025-03-29,2025-04-12,ICU,91
21,PAT-ba5529f4,Dustin Jordan,45,2025-06-14,2025-06-20,general_medicine,80