truncate the rows

In [2]:
import pandas as pd

df = pd.read_csv("../data/patients.csv")
df.head(6)

,patient_id,name,age,arrival_date,departure_date,service,satisfaction
0,PAT-09484753,Richard Rodriguez,24,2025-03-16,2025-03-22,surgery,61
1,PAT-f0644084,Shannon Walker,6,2025-12-13,2025-12-14,surgery,83
2,PAT-ac6162e4,Julia Torres,24,2025-06-29,2025-07-05,general_medicine,83
3,PAT-3dda2bb5,Crystal Johnson,32,2025-10-12,2025-10-23,emergency,81
4,PAT-08591375,Garrett Lin,25,2025-02-18,2025-02-25,ICU,76
5,PAT-f4b29bae,Diana May,83,2025-06-26,2025-06-30,emergency,81

In [6]:
df=df.sort_index(axis = 1)

In [7]:
df.truncate('name','service',axis =1)

                  name    patient_id  satisfaction           service
0    Richard Rodriguez  PAT-09484753            61           surgery
1       Shannon Walker  PAT-f0644084            83           surgery
2         Julia Torres  PAT-ac6162e4            83  general_medicine
3      Crystal Johnson  PAT-3dda2bb5            81         emergency
4          Garrett Lin  PAT-08591375            76               ICU
..                 ...           ...           ...               ...
995         Amber Vang  PAT-a01bf534            91         emergency
996       Martha Smith  PAT-87fa07bd            99         emergency
997     Jennifer James  PAT-8f07e894            69               ICU
998     Kara Hernandez  PAT-4ae301e1            61               ICU
999    Lorraine Turner  PAT-e2ef9c5f            83  general_medicine

[1000 rows x 4 columns]